# Generated by Django 5.2.8 on 2025-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='password',
        ),
        migrations.AddField(
            model_name='room',
            name='members_status_json',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='room',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
    ]
