# Generated by Django 5.2.8 on 2025-12-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_room_password_room_members_status_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='members_status_json',
        ),
        migrations.RemoveField(
            model_name='room',
            name='requires_approval',
        ),
    ]
