# Generated by Django 5.2.8 on 2025-12-03 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_room_members_status_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_username', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved Member')], default='PENDING', max_length=10)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.room')),
            ],
            options={
                'unique_together': {('room', 'member_username')},
            },
        ),
    ]
