# Generated by Django 5.2.8 on 2025-12-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_room_requires_approval_roommembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='requires_approval',
        ),
        migrations.DeleteModel(
            name='RoomMembership',
        ),
    ]
