# Generated by Django 5.2.8 on 2025-12-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_room_requires_approval_delete_roommembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='pending_requesters',
            field=models.JSONField(default=list),
        ),
    ]
