# Generated by Django 5.2.8 on 2025-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_room_pending_requesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='secret_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
