# Generated by Django 5.2.8 on 2025-12-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_message_parent_message_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='external_attachment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
