"""
Django settings for ChatProject project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/#Tdatabases
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-change-this-before-running-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '192.168.100.57', # <-- Your Host Machine's IP
    # '192.168.1.4',
    '*' # <-- Allows any device on your local network
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',  # Required for Django Channels
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ChatProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ChatProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'myappdb',  # Corresponds to MYSQL_DATABASE in docker-compose.yml
        'USER': 'user',      # Corresponds to MYSQL_USER
        'PASSWORD': 'password123', # Corresponds to MYSQL_PASSWORD
        'HOST': 'db',        # Corresponds to the service name in docker-compose.yml
        # 'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# 🔑 1. DIRECTORIES WHERE DJANGO LOOKS FOR STATIC FILES IN APPS (like your chat/static/ folder)
STATICFILES_DIRS = [
    # This line is usually not strictly necessary if you put static files inside
    # an app's 'static' folder, but including it for robustness:
    os.path.join(BASE_DIR, 'static'),
]

# 🔑 2. THE ABSOLUTE FILESYSTEM PATH TO THE DIRECTORY WHERE collectstatic WILL GATHER FILES
# This directory MUST exist and MUST NOT be the same as any directory listed in STATICFILES_DIRS.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build')

# Media Files (Uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels/ASGI Configuration
ASGI_APPLICATION = "ChatProject.asgi.application"

# --- Channels Layer Configuration (UNCHANGED) ---
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # Use the service name 'redis' from docker-compose.yml
            "hosts": [("redis", 6379)],
            
        },
    },
}

# --- CRITICAL NEW CACHE CONFIGURATION ---
# This is necessary for django.core.cache (used for the Grace Period timer)
CACHES = {
    'default': {
        # Using Redis Cache backend, which is best practice when using Redis for Channels
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://redis:6379/1', # Use database 1 for cache, 0 for channels (default)
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Optionally, enable the setting to track if the connection is active
            'IGNORE_EXCEPTIONS': True, 
        }
    }
}

# NOTE: You will need to install the 'django-redis' library 
# (e.g., pip install django-redis)